/* Provider credentials and evidence remain server controlled. */
(() => {
'use strict';
const $=id=>document.getElementById(id), make=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls||'';n.textContent=text||'';return n;};
const form=$('composer'),q=$('query'),thread=$('thread'),empty=$('empty'),fine=document.querySelector('.fineprint'),dock=document.querySelector('.dock-inner');
let parent=null,active=null,available=false,version=0,history=[];
try{history=JSON.parse(localStorage.getItem('zearch:research-history')||'[]').filter(x=>/^[a-f0-9]{32}$/.test(x.id)).slice(0,100);}catch{}
const notice=make('p','research-notice','Checking research availability…');notice.setAttribute('role','status');empty.append(notice);
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),4000);}
function closeRail(){$('shell').classList.remove('rail-open');}
function controls(){$('decide').disabled=!active&&(!available||!q.value.trim());$('decide').querySelector('span').textContent=active?'Stop':'Search';$('decide').setAttribute('aria-label',active?'Stop research':'Search');q.style.height='auto';q.style.height=Math.min(q.scrollHeight,180)+'px';}
function listHistory(){$('history').replaceChildren();history.forEach(item=>{const li=make('li'),b=make('button','h-q',item.query);b.onclick=()=>{if(!active){location.hash='r/'+item.id;closeRail();}};li.append(b);$('history').append(li);});if(!history.length)$('history').append(make('li','h-empty','Your discoveries will appear here.'));}
function remember(run){history=[{id:run.id,query:run.query},...history.filter(x=>x.id!==run.id)].slice(0,100);try{localStorage.setItem('zearch:research-history',JSON.stringify(history));}catch{}listHistory();}
function showThread(){empty.classList.add('hidden');form.classList.remove('home-composer');dock.append(form,fine);}
function home(){if(active)return;version++;parent=null;thread.replaceChildren();empty.classList.remove('hidden');empty.insertBefore(form,notice);empty.insertBefore(fine,notice);form.classList.add('home-composer');window.history.replaceState(null,'',location.pathname);q.value='';controls();q.focus();closeRail();}
function link(source,text){let url;try{url=new URL(source.url);}catch{return document.createTextNode(text);}if(!['https:','http:'].includes(url.protocol))return document.createTextNode(text);const a=make('a','citation',text);a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';a.title=source.title;return a;}
function prose(node,text,sources){node.replaceChildren();for(const block of text.split(/\n\s*\n/)){const p=make('p');for(const part of block.split(/(\[\d+\])/g)){const m=part.match(/^\[(\d+)\]$/),s=m&&sources.find(x=>x.n===Number(m[1]));p.append(s?link(s,part):document.createTextNode(part));}node.append(p);}}
function turn(run){const root=make('article','turn'),question=make('div','user-message'),response=make('section','assistant-message'),status=make('p','research-status'),body=make('div','research-prose'),details=make('details','research-evidence'),summary=make('summary'),sources=make('ol'),copy=make('button','ghost-btn','Copy');question.append(make('div','user-bubble',run.query));response.setAttribute('aria-label','Zearch answer');status.setAttribute('role','status');details.append(summary,sources);copy.onclick=async()=>{try{await navigator.clipboard.writeText(run.answer||'');toast('Answer copied');}catch{toast('Copy is unavailable');}};response.append(status,body,details,copy);root.append(question,response);thread.append(root);
function update(){prose(body,run.answer||'',run.sources||[]);status.textContent=run.error||(run.status==='complete'?'':run.status==='interrupted'?'Stopped · partial answer':'Research in progress');if(run.usage?.citation_warnings?.length)status.textContent=run.usage.citation_warnings.join(' ');copy.hidden=!run.answer||!['complete','error','interrupted'].includes(run.status);sources.replaceChildren();for(const s of run.sources||[]){const li=make('li');li.append(link(s,s.title||s.domain),make('p','',s.excerpt));sources.append(li);}details.hidden=!sources.children.length;summary.textContent=sources.children.length+' sources';}update();return{run,update,status,body};}
async function route(){if(active)return;const id=location.hash.match(/^#r\/([a-f0-9]{32})$/)?.[1];if(!id)return home();const rev=++version;try{const records=[],seen=new Set();let next=id;while(next&&records.length<20&&!seen.has(next)){seen.add(next);const response=await fetch('/api/research?id='+next),record=await response.json();if(!response.ok)throw Error(record.error||'Could not open research');records.unshift(record);next=record.parent_id;}if(rev!==version)return;thread.replaceChildren();showThread();records.forEach(turn);parent=records.at(-1)?.status==='complete'?id:null;if(next)toast('Showing the latest 20 answers');}catch(e){if(rev===version){home();toast(e.message);}}}
async function submit(event){event.preventDefault();if(active){active.abort();return;}const question=q.value.trim();if(!question||!available)return;version++;active=new AbortController();showThread();const view=turn({query:question,answer:'',sources:[],status:'pending'});q.value='';controls();let complete=false;
function accept(data){const feed=$('feed'),follow=feed.scrollHeight-feed.scrollTop-feed.clientHeight<160;if(data.type==='start'){view.run.id=data.id;remember(view.run);window.history.replaceState(null,'','#r/'+data.id);}if(data.type==='status')view.status.textContent=data.text;if(data.type==='sources'){view.run.sources=data.sources;view.update();}if(data.type==='delta'){view.run.answer+=data.text;prose(view.body,view.run.answer,view.run.sources);}if(data.type==='complete'){Object.assign(view.run,data.run);parent=data.run.id;complete=true;view.update();}if(data.type==='error')throw Error(data.error);if(follow)feed.scrollTop=feed.scrollHeight;}
try{const response=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},signal:active.signal,body:JSON.stringify({query:question,parent_id:parent,request_id:crypto.randomUUID()})});if(!response.ok){const data=await response.json();throw Error(data.error||'Research unavailable');}if(response.headers.get('Content-Type')?.includes('application/json')){const data=await response.json();Object.assign(view.run,data.run);view.update();complete=data.run.status==='complete';if(complete)parent=data.run.id;}else{const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';try{while(true){const{value,done}=await reader.read();buffer+=decoder.decode(value,{stream:!done});let at;while((at=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,at);buffer=buffer.slice(at+1);if(line.trim())accept(JSON.parse(line));}if(done)break;}}finally{reader.releaseLock();}}if(!complete)throw Error('Research ended before completion. Any partial answer is incomplete.');}catch(e){active.abort();view.run.status='interrupted';view.run.error=e.name==='AbortError'?'Stopped · any partial answer is incomplete.':e.message;view.update();}finally{active=null;controls();q.focus();}}
form.addEventListener('submit',submit);q.addEventListener('input',controls);q.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();form.requestSubmit();}});$('new-btn').onclick=home;$('brand').onclick=e=>{e.preventDefault();home();};$('clear-history').onclick=()=>{history=[];try{localStorage.removeItem('zearch:research-history');}catch{}listHistory();toast('Local shortcuts cleared');};$('btn-settings').onclick=()=>$('settings').showModal();$('btn-thesis').onclick=()=>$('thesis').showModal();$('menu-btn').onclick=()=>$('shell').classList.add('rail-open');$('rail-close').onclick=closeRail;$('scrim').onclick=closeRail;document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();home();}if(e.key==='Escape')closeRail();});window.addEventListener('hashchange',route);listHistory();controls();route();fetch('/api/research').then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{available=data.available;notice.textContent=available?'':'Live research is being configured. Please check back shortly.';controls();}).catch(()=>{notice.textContent='Research is temporarily unavailable. Please try again later.';});
})();
